### ISSUE TITLE
Add make option

### ISSUE THREAD

**Issue by Astaelan** [lordmilko/i686-elf-tools#11] opened 2021-08-11 20:13 UTC
As is the obvious, I'm working on setting up an OS kernel dev environment and I want to use Visual Studio 2019 with a Makefile Project. To do this, I need make added to the list. I've manually added this to my own copy of your scripts and am in the process of rebuilding the docker file and building a new toolchain, but it might be worth adding as an option for building make to your script.
I also ran into an issue with your Dockerfile, since you use ubuntu for the base image, you need to add the following 2 lines to the Dockerfile or it gets stuck asking for tzdata and refuses to accept user input.
```
ENV TZ=Asia/Dubai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```
Substitute Asia/Dubai for your preferred default TZ, for bonus points consider using SED/AWK to grab the timezone from the host system as a preferred default using:
```
timedatectl | grep "Time zone"
```

**Comment by lordmilko** [comment] 2021-08-11 22:40
Hi @Astaelan,

The main purpose of this project is to provide users with an i686-elf toolchain that they can then use to go off and go their own thing. I use this toolchain in Visual Studio with [VisualGDB](https://github.com/lordmilko/VSKernelDev) although understandably that may not be an option for everyone.

Are you able to advise why exactly you need this repo to build `make`? Wouldn't you simply install make from your distro's package manager and off you go?

I will look at why Ubuntu is asking for timezone data, potentially some dependencies used by the Dockerfile have changed since I first wrote it

Regards,
lordmilko

**Comment by Astaelan** [comment] 2021-08-12 00:05
In the case of windows tooling, when I'm building an i686-elf toolchain to compile 32bit elf binaries from windows, I also would like to have a make that runs on windows, but this is all getting built on a linux box as part of the toolchain prereqs. Likewise the same tools then are available and used on linux regardless of the host being x86_64 or something else.
It might be easiest for me at this point to just grab a precompiled make, mkisofs, and qemu to include those manually.  Eventually need to look at something like newlib to provide the stdclib and something similar for C++ as well and break it down to a handful of system calls I actually need to implement, so perhaps including newlib as an option could be considered as well.

For a bit more insight into what I'm actually doing, I'll keep it short, but I want to add the Core .NET RyuJIT into a kernel and be able to JIT compile IL to write most of the OS in C# after getting 32bit protected mode running enough to setup memory management.

So I need a decent build system that's going to let me not only compile my kernel code, but also all the JIT code into it which includes both standard C and C++ lib requirements (and currently appears to use CMake/Make to build the whole foundational dotnet/runtime repository).  And ultimately I want to be able to run the same makefiles and scripts on windows or linux to do the builds, less maintenance.  So a windows "make" precompiled MXE type binary is really what I need (statically linked). And then of course cmake ontop of that to produce more cross platform friendly makefiles.

**Comment by lordmilko** [comment] 2021-08-12 01:44
Thanks @Astaelan,

Writing a kernel in C# definitely sounds better than doing in C++! Based on your description I think it would be best to have an *install dependencies* script that installs the appropriate dependencies of your build system based on whether you are running on Windows, Linux or whatever. This script would then download and install precompiled versions of make, qemu or whatever; while MXE's statically linked binaries are definitely very *cool*, I don't know whether you necessarily *need* them for all build components.

If you don't actually need to use a newer version of gcc you could even simply programmatically download and extract the appropriate zip file on the [releases](https://github.com/lordmilko/i686-elf-tools/releases/tag/7.1.0) page. Compiling i686-elf-tools yourself takes a very long time!

I have managed to reproduce the issue with tzdata prompting for input and am investigating the best way of resolving this - thanks for bringing this to my attention!

**Comment by Astaelan** [comment] 2021-08-12 05:27
It would be nice to have a quick script to run and the entire toolchain is built, even if it takes a couple hours, particularly a few years into the future when latest versions might not be so easy to build or use.
That said, I went ahead and built a new toolchain using conventional manual build with the newest GCC and binutils and it went good, I have bare kernel compiling and running under linux, so I just need to make a new canadian cross compile for a windows toolchain when I am ready.
But from here I still think I'll need a precompiled make/qemu/etc because building it for a target system (specifically windows) seems to be giving issues with lacking pwd.h, however the linux build worked.
Thanks for your feedback, I'll probably end up just using precompiled binaries.

**Closed as completed** 2021-08-12 07:12 UTC
